version: "3.9"
services:
  app:
    env_file:
      - .development.env
    container_name: awesome_nest_boilerplate
    restart: always
    build: .
    ports:
      - 3000:3000

  # postgres:
  #   image: postgres:13
  #   restart: always
  #   env_file:
  #     - .development.env
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #     - ./scripts/init-db-script.sh:/docker-entrypoint-initdb.d/init-db-script.sh

# volume:
  # db-data:
