version: "3.9"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'development'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1q2w3e4r'
      MYSQL_ROOT_PASSWORD: '1q2w3e4r'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - ./scripts/init-db-script.sh:/docker-entrypoint-initdb.d/init-db-script.sh